[package]
name = "bdat-toolset"
version = "0.1.0"
edition = "2021"
license = "gpl-3.0"

[dependencies]
bdat = {path = "../"}
clap = { version = "4.0.8", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fasthash = "0.4"

[features]